url: "https://enricobilla.github.io"
baseurl: "/"
title: "Enrico Brambilla"

author:
  fullname: "Enrico Brambilla"
  instagram: "enrico.brambilla"
  github: "EnricoBilla"
  linkedin: "enrico-brambilla-8627b4211"
  email: "enric.brambilla+ws@gmail.com"
  telegram: "enricobilla"

plugins:
  - jekyll-postcss